import uuid
from django.db import models
from datetime import datetime
from .post import Post


class Comment(models.Model):
    # unique comments ID's are generated by the database
    type = models.TextField(default="comment", editable=False)
    comment_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.JSONField()
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    content_type = models.TextField(default='text/plain')
    created_at = models.DateTimeField("date commented", default=datetime.now)