from django.db import models
from datetime import datetime
from .user import User
from .post import Post


class Comment(models.Model):
    # unique comments ID's are generated by the database
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    content_type = models.CharField(max_length=50) # e.g text/markdown?
    created_at = models.DateTimeField("date commented", default=datetime.now)