from django.db import models
from datetime import datetime
from .user import User
from .post import Post


class Comment(models.Model):
    # unique comments ID's are generated by the database
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    datePosted = models.DateTimeField("date commented", default=datetime.now)