from datetime import datetime
from django.db import models
from .user import User

# only account for cases where (local or remote) user wants to follow local users

class FollowRequest(models.Model):
    # unique follow request ID's are generated by the database
    type = models.TextField(default="follow", editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='user') # always local
    requester = models.JSONField(default=dict) # can be local or remote objects
    created_at = models.DateTimeField(default=datetime.now)
