from datetime import datetime
from django.db import models
from .user import User

class FollowRequest(models.Model):
    # unique follow request ID's are generated by the database
    type = models.TextField(default="follow", editable=False)
    summary = models.CharField(max_length=100, null=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='user')
    requester = models.JSONField(default=dict)
    created_at = models.DateTimeField(default=datetime.now)
