from datetime import datetime
from django.db import models
from .user import User

class Follow(models.Model):
    # unique follow ID's are generated by the database
    # "follower" is the user who followed the "followee"
    # each follow relationship must have either local_follower or local_followee or both but never neither
    local_follower = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='local_follower')
    remote_follower = models.URLField(null=True, blank=True)
    local_followee = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='local_followee')
    remote_followee = models.URLField(null=True, blank=True) # must use the full URL of the followed author, for both local or remote nodes
    created_at = models.DateTimeField("date followed", default=datetime.now)

    def __str__(self):
        follower = self.local_follower.username if self.local_follower else self.remote_follower
        followee = self.local_followee.username if self.local_followee else self.remote_followee
        return f"{follower} follows {followee}"
