from django.db import models
from datetime import datetime
from .user import User

class Follow(models.Model):
    # unique follow ID's are generated by the database
    # "follower" is the user who followed the "followee"
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    followee = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followee")
    timeFollowed = models.DateTimeField("date followed", default=datetime.now)
