from datetime import datetime
from django.db import models
from .user import User
from .post import Post

class Like(models.Model):
    # unique like ID's are generated by the database
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField("date liked", default=datetime.now)