from django.db import models
from datetime import datetime
from .user import User
from .post import Post

class Like(models.Model):
    # unique like ID's are generated by the database
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    dateLiked = models.DateTimeField("date liked", default=datetime.now)