from datetime import datetime
import uuid
from django.db import models
from .post import Post

class Like(models.Model):
    # unique like ID's are generated by the database
    type = models.TextField(default="like", editable=False)
    user = models.JSONField(default=dict) # to account for remote users
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
    remote_post = models.URLField(blank=True, null=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    created_at = models.DateTimeField("date liked", default=datetime.now)