import uuid
from django.db import models
from datetime import datetime
from .user import User

class Post(models.Model):
    # unique post ID's are generated by the database
    type = models.TextField(default="post", editable=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    github_id = models.CharField(max_length=200, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True)
    
    has_image = models.BooleanField(default=False)
    content_type = models.CharField(
        choices=[
            ('text/plain', 'UTF-8'),
            ('text/markdown', 'CommonMark'), 
            ('image/png;base64', 'PNG Image (Base64)'),
            ('image/jpeg;base64', 'JPEG Image (Base64)'),
            ('application/base64', 'Other Base64 Data')
        ],
        default='text/plain',
        max_length=20
    )
    content = models.TextField(null=True, blank=True) # base64-encoded image or just normal text
    
    VISIBILITY_CHOICES = [
        (1, 'PUBLIC'),
        (2, 'FRIENDS'),
        (3, 'UNLISTED'),
        (4, 'DELETED'),
    ]
    visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=1)
    created_at = models.DateTimeField("date posted", default=datetime.now)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        """String representation for the post object (useful for admin panels)."""
        return f"{self.title} ({self.uuid}) by ({self.user.display_name})"
