from django.db import models
from datetime import datetime
from .user import User

class Post(models.Model):
    # unique post ID's are generated by the database
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=2000)
    has_image = models.BooleanField(default=False)
    # To have multiple Images in one Post, must create a separate Image model and link to Post via a ForeignKey
    image = models.ImageField(upload_to='post_images/')
    content_type = models.CharField(max_length=50)  # e.g., 'text/plain', 'text/markdown', etc.
    VISIBILITY_CHOICES = [
        (1, 'PUBLIC'),
        (2, 'FRIENDS'),
        (3, 'UNLISTED'),
        (4, 'DELETED'),
    ]
    visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=1)
    created_at = models.DateTimeField("date posted", default=datetime.now)
    modified_at = models.DateTimeField(auto_now=True)