from django.db import models
from datetime import datetime
from .user import User

class Post(models.Model):
    # unique post ID's are generated by the database
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    hasImage = models.BooleanField(default=False)
    image = models.ImageField() # unsure if this restricts users to only one image per post
    likes = models.IntegerField()
    status = models.CharField(max_length=12) # can be "Public", "Unlisted", "Friends-Only", or "Deleted"
    datePosted = models.DateTimeField("date posted", default=datetime.now)