from django.db import models
from datetime import datetime

class User(models.Model):
    # user unique ID's are generated by the database
    name = models.CharField(max_length=20)
    userID = models.IntegerField()
    profilePicture = models.ImageField()
    createdAt = models.DateTimeField(auto_now_add=True)