from django.db import models
from django.urls import reverse
import uuid

class User(models.Model): # is basically the Author(s)
    # user unique ID's are generated by the database
    name = models.CharField(max_length=20)
    user_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True) # is the UUID, will be used in the API URLs to identify author across nodes
    profile_image = models.ImageField(upload_to='profile_pictures/') # should be saved under BASE_DIR/azureDNS/media/profile_pictures/<filename>.jpg
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True) # Auto-update on every save

    def __str__(self):
        """String representation for the author object (useful for admin panels)."""
        return f"{self.name} ({self.uuid})"
    
    def get_absolute_url(self):
        """
        Returns the unique URL for this author, which will look like:
        http://node1/api/authors/<uuid>
        """
        return reverse('author-detail', args=[str(self.uuid)])
    
    # github, page, and host is not saved yet
