from datetime import datetime
from django.db import models
from django.urls import reverse
import uuid

class User(models.Model):
    # user unique ID's are generated by the database
    type = models.TextField(default="author", editable=False)
    user_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    host = models.URLField(null=True) # The full API URL for the author's node (e.g. http://nodeaaaa/api/)
    display_name = models.CharField(max_length=20)
    github = models.URLField(null=True) # e.g. "http://github.com/gjohnson"
    page = models.URLField(null=True) # e.g. "http://nodebbbb/authors/222"
    profile_image = models.ImageField(upload_to='profile_pictures/', null=True) # should be saved under BASE_DIR/azureDNS/media/profile_pictures/<filename>.jpg
    created_at = models.DateTimeField(default=datetime.now)
    modified_at = models.DateTimeField(auto_now=True) # Auto-update on every save

    def __str__(self):
        """String representation for the author object (useful for admin panels)."""
        return f"{self.display_name}: ({self.uuid})"
    
    def get_full_url(self):
        """
        Returns the unique URL for this author, which will look like:
        http://node1/api/authors/<uuid>
        """
        return f"{self.host}authors/{self.user_id}"
