# Generated by Django 5.1.1 on 2024-10-04 18:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userID', models.IntegerField()),
                ('profilePicture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('hasImage', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
                ('datePosted', models.DateTimeField(default=datetime.datetime.now, verbose_name='date posted')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLiked', models.DateTimeField(default=datetime.datetime.now, verbose_name='date liked')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFollowed', models.DateTimeField(default=datetime.datetime.now, verbose_name='date followed')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='azureDSN.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='azureDSN.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('datePosted', models.DateTimeField(default=datetime.datetime.now, verbose_name='date commented')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.user')),
            ],
        ),
    ]
