# Generated by Django 5.1.1 on 2024-10-14 20:56

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=2000, null=True)),
                ('has_image', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('content_type', models.TextField(default='text/plain')),
                ('visibility', models.IntegerField(choices=[(1, 'PUBLIC'), (2, 'FRIENDS'), (3, 'UNLISTED'), (4, 'DELETED')], default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date posted')),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('type', models.TextField(default='author', editable=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(null=True)),
                ('display_name', models.CharField(max_length=20)),
                ('github', models.URLField(null=True)),
                ('page', models.URLField(null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('unused_payload', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='like', editable=False)),
                ('user', models.JSONField(default=dict)),
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date liked')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='comment', editable=False)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.JSONField(default=dict)),
                ('content', models.CharField(max_length=500)),
                ('content_type', models.TextField(default='text/plain')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date commented')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.user'),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='azureDSN.inboxitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureDSN.user')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='follow', editable=False)),
                ('requester', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='azureDSN.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_follower', models.URLField(blank=True, null=True)),
                ('remote_followee', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date followed')),
                ('local_followee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_followee', to='azureDSN.user')),
                ('local_follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_follower', to='azureDSN.user')),
            ],
        ),
    ]
