# Generated by Django 5.1.1 on 2024-10-30 04:17

from django.db import migrations

# This is important! So that admin can toggle user registration approval setting.
def create_site_configuration(apps, schema_editor):
    SiteConfiguration = apps.get_model('azureDSN', 'SiteConfiguration')
    if not SiteConfiguration.objects.exists():
        SiteConfiguration.objects.create(require_approval=True)

class Migration(migrations.Migration):
    dependencies = [
        ('azureDSN', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site_configuration),
    ]
