# Generated by Django 5.1.1 on 2024-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.JSONField(default=dict),
        ),
    ]
