# Generated by Django 5.1.1 on 2024-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0002_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.JSONField(db_column='user', default=dict),
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
