# Generated by Django 5.1.1 on 2024-10-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0002_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.JSONField(db_column='user', default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'UTF-8'), ('text/markdown', 'CommonMark'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)'), ('application/base64', 'Other Base64 Data')], default='text/plain', max_length=20),
        ),
    ]
