# Generated by Django 5.1.1 on 2024-10-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0002_alter_post_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
