# Generated by Django 5.1.1 on 2024-10-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0003_remove_comment_likes_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
