# Generated by Django 5.1.1 on 2024-10-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0003_rename_user_id_post_user_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uuid',
        ),
    ]
