# Generated by Django 5.1.1 on 2024-10-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
