# Generated by Django 5.1.1 on 2024-11-02 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0004_post_github_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.URLField()),
                ('post', models.URLField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date reposted')),
            ],
        ),
    ]
