# Generated by Django 5.1.1 on 2024-10-13 19:37

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0004_inboxitem_inbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datePosted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postID',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='timeFollowed',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='dateLiked',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='postID',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datePosted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hasImage',
            new_name='has_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='like',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.TextField(default='text/plain'),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.TextField(default='comment', editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='follow',
            name='local_followee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_followee', to='azureDSN.user'),
        ),
        migrations.AddField(
            model_name='follow',
            name='local_follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_follower', to='azureDSN.user'),
        ),
        migrations.AddField(
            model_name='follow',
            name='remote_followee',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='remote_follower',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.TextField(default='like', editable=False),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.TextField(default='text/plain'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'PUBLIC'), (2, 'FRIENDS'), (3, 'UNLISTED'), (4, 'DELETED')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='page',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(default='author', editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
