# Generated by Django 5.1.1 on 2024-10-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0004_rename_id_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='inboxitem',
            old_name='unused_payload',
            new_name='remote_payload',
        ),
    ]
