# Generated by Django 5.1.1 on 2024-10-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0005_rename_user_id_followrequest_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='requester',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='followrequest',
            old_name='user',
            new_name='object',
        ),
    ]
