# Generated by Django 5.1.1 on 2024-10-14 05:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0005_rename_dateposted_comment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='follow', editable=False)),
                ('requester', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='azureDSN.user')),
            ],
        ),
    ]
