# Generated by Django 5.1.1 on 2024-11-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0006_share_recevier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='recevier',
            new_name='receiver',
        ),
    ]
