# Generated by Django 5.1.1 on 2024-11-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0007_rename_recevier_share_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.TextField(default='share', editable=False),
        ),
    ]
