# Generated by Django 5.1.1 on 2024-10-18 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0007_rename_content_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_id',
        ),
        migrations.AddField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(default='post', editable=False),
        ),
    ]
