# Generated by Django 5.1.1 on 2024-11-04 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0008_share_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
