# Generated by Django 5.1.1 on 2024-11-07 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0009_inboxitem_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('azureDSN.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
