# Generated by Django 5.1.1 on 2024-11-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0010_alter_share_receiver_alter_share_user'),
        ('azureDSN', '0011_alter_user_profile_image'),
    ]

    operations = [
    ]
