# Generated by Django 5.1.1 on 2024-11-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0012_merge_20241110_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='post_status',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
