# Generated by Django 5.1.1 on 2024-11-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0013_inboxitem_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='remote_object',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='remote_pending',
            field=models.BooleanField(default=False),
        ),
    ]
