# Generated by Django 5.1.1 on 2024-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0013_inboxitem_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeuser',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
