# Generated by Django 5.1.1 on 2024-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0014_alter_nodeuser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='remote_post',
            field=models.URLField(blank=True, null=True),
        ),
    ]
