# Generated by Django 5.1.1 on 2024-11-24 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0014_alter_nodeuser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='remote_post',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azureDSN.post'),
        ),
    ]
