# Generated by Django 5.1.2 on 2024-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureDSN', '0015_like_remote_post_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='remote_post',
            field=models.URLField(blank=True, null=True),
        ),
    ]
