
from rest_framework import serializers
from ..models import Like, Post
from .user import UserSerializer


class LikeSerializer(serializers.ModelSerializer):
    author = UserSerializer()

    class Meta:
        model = Like
        fields = ('type', 'author', 'published', 'id', 'object')

    def create(self, validated_data):
        """Create new Like object"""
        author_data = validated_data.pop('author') # json/dict object

        object_url = validated_data['object'] # the Post object URL
        post_id = object_url.split('/')[-1] # seems like the Post 'id' is always the last part of the URL

        try:
            post = Post.objects.get(id=post_id)
        except Post.DoesNotExist:
            raise serializers.ValidationError(f"Post with id '{post_id}' does not exist.")

        # like_id = f"{service}/{author_data['id'].split('/')[-1]}/liked/{like_uuid}"

        post = Post.objects.get(id=post_id)
        like = Like.objects.create(
            user=author_data,
            post_id=post,
            # like_id=like_uuid, # generated by default in DB
            **validated_data
        ) # save Like object to DB

        return like
        
        # # Generate JSON object to be sent to target user's inbox
        # like_json = {
        #     "type": "like",
        #     "author": author_data,
        #     "published": validated_data.get('published', datetime.now().isoformat()),
        #     "id": like_id,
        #     "object": object_url,
        # }

        # return like_json
    

    