from django.db import models
from datetime import datetime

# Create your models here.

class User(models.Model):
    # user unique ID's are generated by the database
    name = models.CharField(max_length=20)
    userID = models.IntegerField()
    profilePicture = models.ImageField()
    
class Follow(models.Model):
    # unique follow ID's are generated by the database
    # "follower" is the user who followed the "followee"
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    followee = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followee")
    timeFollowed = models.DateTimeField("date followed", default=datetime.now)

class Post(models.Model):
    # unique post ID's are generated by the database
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    hasImage = models.BooleanField(default=False)
    image = models.ImageField() # unsure if this restricts users to only one image per post
    likes = models.IntegerField()
    status = models.CharField(max_length=12) # can be "Public", "Unlisted", "Friends-Only", or "Deleted"
    datePosted = models.DateTimeField("date posted", default=datetime.now)

class Like(models.Model):
    # unique like ID's are generated by the database
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    dateLiked = models.DateTimeField("date liked", default=datetime.now)

class Comment(models.Model):
    # unique comments ID's are generated by the database
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    datePosted = models.DateTimeField("date commented", default=datetime.now)
# Create your models here.
